// <auto-generated />
using HomeyBackend.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeyBackend.Migrations
{
    [DbContext(typeof(HomeyBackendDbContext))]
    [Migration("20240723161143_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeyBackend.Core.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceDetailBooleanId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceDetailNumberRoomsId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceDetailBooleanId")
                        .IsUnique();

                    b.HasIndex("PlaceDetailNumberRoomsId")
                        .IsUnique();

                    b.ToTable("Places");
                });

            modelBuilder.Entity("HomeyBackend.Core.Models.PlaceDetailBoolean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Elevator")
                        .HasColumnType("bit");

                    b.Property<bool>("Furntiure")
                        .HasColumnType("bit");

                    b.Property<bool>("Garden")
                        .HasColumnType("bit");

                    b.Property<bool>("Pool")
                        .HasColumnType("bit");

                    b.Property<bool>("SolarPower")
                        .HasColumnType("bit");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PlaceDetailBooleans");
                });

            modelBuilder.Entity("HomeyBackend.Core.Models.PlaceDetailNumberRooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfBaths")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSalons")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlacesDetailNumbers");
                });

            modelBuilder.Entity("HomeyBackend.Core.Models.Place", b =>
                {
                    b.HasOne("HomeyBackend.Core.Models.PlaceDetailBoolean", "PlaceDetailBoolean")
                        .WithOne("Place")
                        .HasForeignKey("HomeyBackend.Core.Models.Place", "PlaceDetailBooleanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeyBackend.Core.Models.PlaceDetailNumberRooms", "PlaceDetailNumberRooms")
                        .WithOne("Place")
                        .HasForeignKey("HomeyBackend.Core.Models.Place", "PlaceDetailNumberRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaceDetailBoolean");

                    b.Navigation("PlaceDetailNumberRooms");
                });

            modelBuilder.Entity("HomeyBackend.Core.Models.PlaceDetailBoolean", b =>
                {
                    b.Navigation("Place")
                        .IsRequired();
                });

            modelBuilder.Entity("HomeyBackend.Core.Models.PlaceDetailNumberRooms", b =>
                {
                    b.Navigation("Place")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
